"""
Re-generate the chain-of-thought of a MetaMath SFT dataset with Qwen3-0.6B.

Source dataset: Dicksonycx/oumi_math_4096
    Each row has a `messages` field of the form
        [
            {"role": "user",      "content": <math_question>},
            {"role": "assistant", "content": "<think>{r1_thinking}</think>{r1_answer}"},
        ]
    The thinking text was generated by DeepSeek-R1.

We take the first 5000 rows and ask Qwen3-0.6B to *rephrase and reorganize*
the whole reasoning in its own words (re-solving the problem in thinking mode),
then collect its output as the new assistant turn.

Three datasets are pushed to the Hub:
    Dicksonycx/MetaMath-Original         -> the original 5000 rows (untouched)
    Dicksonycx/MetaMath-ReGenerate       -> new think + new answer (full Qwen3 output)
    Dicksonycx/MetaMath-ReGenerateThink  -> new think only

Run on a GPU (e.g. A100-40GB):
    pip install vllm datasets huggingface_hub
    python utils/transform_msg.py                 # full run + push
    python utils/transform_msg.py --limit 8 --no-push   # quick smoke test
"""

import os
import re
import argparse
from pathlib import Path

from datasets import load_dataset, Dataset
from huggingface_hub import login

# ── config ─────────────────────────────────────────────────────────────
SOURCE_REPO    = "Dicksonycx/oumi_math_4096"
N_SAMPLES      = 5000
MODEL_NAME     = "Qwen/Qwen3-0.6B"
MAX_NEW_TOKENS = 4096
MAX_MODEL_LEN  = 8192

REPO_ORIGINAL = "Dicksonycx/MetaMath-Original"
REPO_REGEN    = "Dicksonycx/MetaMath-ReGenerate"
REPO_REGEN_TH = "Dicksonycx/MetaMath-ReGenerateThink"

# Qwen3 thinking-mode sampling (per the model card)
TEMPERATURE = 0.6
TOP_P       = 0.95
TOP_K       = 20

SYSTEM_PROMPT = (
    "You are a meticulous math tutor. You are given a math problem together with a "
    "reference solution's reasoning. Re-solve the problem from scratch: rephrase and "
    "reorganize the entire reasoning in your own words, restructuring the logical steps "
    "so they are clear, well-ordered and easy to follow. Keep every step mathematically "
    "correct, do not copy the reference wording, and end with the final answer in "
    "\\boxed{}."
)

THINK_RE = re.compile(r"<think>(.*?)</think>(.*)", re.DOTALL)


# ── helpers ────────────────────────────────────────────────────────────
def split_think_answer(text: str):
    """Split assistant content into (thinking, answer)."""
    m = THINK_RE.search(text)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    if "</think>" in text:                     # opening tag missing
        think, answer = text.split("</think>", 1)
        return think.replace("<think>", "").strip(), answer.strip()
    return "", text.strip()                    # no thinking emitted


def normalize_assistant(think: str, answer: str) -> str:
    """Rebuild a `<think>...</think> answer` assistant turn."""
    return f"<think>\n{think}\n</think>\n\n{answer}".strip()


def build_chat(question: str, reference_think: str):
    """Build the chat fed to Qwen3 for one sample."""
    user = (
        f"Problem:\n{question}\n\n"
        f"Reference reasoning (rewrite this in your own words, do not copy it):\n"
        f"{reference_think}"
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user},
    ]


def load_hf_token() -> str | None:
    """Read HF_TOKEN from env or the project .env file."""
    token = os.environ.get("HF_TOKEN")
    if token:
        return token.strip().strip('"').strip("'")
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if line.strip().startswith("HF_TOKEN"):
                _, _, val = line.partition("=")
                return val.strip().strip('"').strip("'")
    return None


# ── main pipeline ──────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=N_SAMPLES,
                        help="number of source rows to process")
    parser.add_argument("--no-push", action="store_true",
                        help="skip pushing to the Hub (local smoke test)")
    parser.add_argument("--save-dir", type=str, default=None,
                        help="optional local dir to save the datasets to disk")
    args = parser.parse_args()

    token = load_hf_token()
    if token:
        login(token=token)

    # 1. load + slice the source dataset ────────────────────────────────
    print(f"Loading {SOURCE_REPO} (first {args.limit} rows)...")
    source = load_dataset(SOURCE_REPO, split=f"train[:{args.limit}]")

    questions, ref_thinks, ref_answers, originals = [], [], [], []
    for row in source:
        msgs = row["messages"]
        question = msgs[0]["content"]
        ref_think, ref_answer = split_think_answer(msgs[-1]["content"])
        questions.append(question)
        ref_thinks.append(ref_think)
        ref_answers.append(ref_answer)
        originals.append(msgs)            # keep full original messages untouched

    # 2. build prompts and generate with vLLM ──────────────────────────
    chats = [build_chat(q, t) for q, t in zip(questions, ref_thinks)]

    print(f"Loading {MODEL_NAME} with vLLM and generating {len(chats)} samples...")
    from vllm import LLM, SamplingParams

    llm = LLM(
        model=MODEL_NAME,
        dtype="bfloat16",
        max_model_len=MAX_MODEL_LEN,
        gpu_memory_utilization=0.90,
    )
    sampling = SamplingParams(
        temperature=TEMPERATURE,
        top_p=TOP_P,
        top_k=TOP_K,
        max_tokens=MAX_NEW_TOKENS,
    )
    outputs = llm.chat(
        chats,
        sampling,
        chat_template_kwargs={"enable_thinking": True},
    )
    generated = [o.outputs[0].text.strip() for o in outputs]

    # 3. assemble the three datasets ────────────────────────────────────
    regen_rows, regen_think_rows = [], []
    n_empty_think = 0
    for question, raw, old_answer in zip(questions, generated, ref_answers):
        new_think, new_answer = split_think_answer(raw)
        if not new_think:
            n_empty_think += 1
        assistant_full = normalize_assistant(new_think, new_answer)

        regen_rows.append({
            "messages": [
                {"role": "user", "content": question},
                {"role": "assistant", "content": assistant_full},
            ]
        })
        regen_think_rows.append({
            "messages": [
                {"role": "user", "content": question},
                {"role": "assistant", "content": normalize_assistant(new_think, old_answer)},
            ]
        })

    ds_original    = Dataset.from_dict({"messages": originals})
    ds_regen       = Dataset.from_list(regen_rows)
    ds_regen_think = Dataset.from_list(regen_think_rows)

    print(f"\nDone. rows={len(ds_regen)}  empty_think={n_empty_think}")
    print("─" * 60)
    print("SAMPLE (regenerated assistant turn):")
    print(ds_regen[0]["messages"][1]["content"][:800])
    print("─" * 60)

    # 4. save / push ────────────────────────────────────────────────────
    if args.save_dir:
        base = Path(args.save_dir)
        ds_original.save_to_disk(str(base / "MetaMath-Original"))
        ds_regen.save_to_disk(str(base / "MetaMath-ReGenerate"))
        ds_regen_think.save_to_disk(str(base / "MetaMath-ReGenerateThink"))
        print(f"Saved datasets to {base}")

    if args.no_push:
        print("--no-push set: skipping Hub upload.")
        return

    print(f"Pushing to {REPO_ORIGINAL} ...")
    ds_original.push_to_hub(REPO_ORIGINAL)
    print(f"Pushing to {REPO_REGEN} ...")
    ds_regen.push_to_hub(REPO_REGEN)
    print(f"Pushing to {REPO_REGEN_TH} ...")
    ds_regen_think.push_to_hub(REPO_REGEN_TH)
    print("All datasets pushed.")


if __name__ == "__main__":
    main()
